/* tslint:disable */
/* eslint-disable */
/**
 * SongGuessBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GeneralSongReadDto
 */
export interface GeneralSongReadDto {
    /**
     * 
     * @type {string}
     * @memberof GeneralSongReadDto
     */
    songName: string;
    /**
     * 
     * @type {string}
     * @memberof GeneralSongReadDto
     */
    songAlbum?: string | null;
}

/**
 * Check if a given object implements the GeneralSongReadDto interface.
 */
export function instanceOfGeneralSongReadDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "songName" in value;

    return isInstance;
}

export function GeneralSongReadDtoFromJSON(json: any): GeneralSongReadDto {
    return GeneralSongReadDtoFromJSONTyped(json, false);
}

export function GeneralSongReadDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeneralSongReadDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'songName': json['songName'],
        'songAlbum': !exists(json, 'songAlbum') ? undefined : json['songAlbum'],
    };
}

export function GeneralSongReadDtoToJSON(value?: GeneralSongReadDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'songName': value.songName,
        'songAlbum': value.songAlbum,
    };
}

