/* tslint:disable */
/* eslint-disable */
/**
 * SongGuessBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SongCreateDto
 */
export interface SongCreateDto {
    /**
     * 
     * @type {string}
     * @memberof SongCreateDto
     */
    songName: string;
    /**
     * 
     * @type {string}
     * @memberof SongCreateDto
     */
    songPath: string;
    /**
     * 
     * @type {number}
     * @memberof SongCreateDto
     */
    songLength: number;
    /**
     * 
     * @type {string}
     * @memberof SongCreateDto
     */
    songAlbum: string;
    /**
     * 
     * @type {string}
     * @memberof SongCreateDto
     */
    songMime: string;
}

/**
 * Check if a given object implements the SongCreateDto interface.
 */
export function instanceOfSongCreateDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "songName" in value;
    isInstance = isInstance && "songPath" in value;
    isInstance = isInstance && "songLength" in value;
    isInstance = isInstance && "songAlbum" in value;
    isInstance = isInstance && "songMime" in value;

    return isInstance;
}

export function SongCreateDtoFromJSON(json: any): SongCreateDto {
    return SongCreateDtoFromJSONTyped(json, false);
}

export function SongCreateDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SongCreateDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'songName': json['songName'],
        'songPath': json['songPath'],
        'songLength': json['songLength'],
        'songAlbum': json['songAlbum'],
        'songMime': json['songMime'],
    };
}

export function SongCreateDtoToJSON(value?: SongCreateDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'songName': value.songName,
        'songPath': value.songPath,
        'songLength': value.songLength,
        'songAlbum': value.songAlbum,
        'songMime': value.songMime,
    };
}

